server:
  port: 8081
  servlet:
    context-path: /home/search
  compression:
    enabled: true
    min-response-size: 2KB
  shutdown: graceful

application:
  id: home-search-service

spring:
  application:
    name: home-search-service
  profiles:
    active: local
  lifecycle:
    timeout-per-shutdown-phase: 1m
  devtools:
    restart:
      enabled: false
  jpa:
    properties:
      hibernate:
        jdbc:
          time_zone: UTC

management:
  endpoint:
    health:
      probes:
        enabled: true
      show-details: always
  endpoints:
    web:
      exposure:
        include: '*'
  health:
    livenessState:
      enabled: true
    readinessState:
      enabled: true




